### ISSUE TITLE
Syntax error with VM that has brackets in it's name/path.

### ISSUE THREAD

**Issue by EaranMaleasi** [JTok/unraid-vmbackup#22]
I get this warning:
![grafik](https://user-images.githubusercontent.com/13442756/71886898-43e3f380-313d-11ea-8d92-2d346e61b43d.png)

The line in question looks like this:
`/mnt/user/domains/FaxSvr.01 (XP)/vdisk1.img="FaxSVR.01 (XP)/vdisk1.img"`

Tried putting the path in quotes, but that threw another warning/error.
So I renamed it to something without brackets.

Would be nice to be able to use brackets in VM names/paths though.

**Comment by JTok** [comment]
This looks like an issue with the plugin and not the script itself, which is what this repository is.
I am going to close this incident here, but I will look into handling parenthesis for VM names and paths over at the main plugin located here:
https://github.com/JTok/unraid.vmbackup

**Comment by JTok** [comment]
This looks like an issue with the plugin and not the script itself, which is what this repository is.
I am going to close this incident here, but I will look into handling parenthesis for VM names and paths over at the main plugin located here:
https://github.com/JTok/unraid.vmbackup

**Comment by JTok** [comment]
Quick update so this is documented:
I have looked into what is causing this, and it seems to be an issue with PHP as far as I can tell.
It looks like it is a problem with parse_ini_file/parse_ini_string. I can't exactly tell if it is an issue the the parenthesis being special characters in the key field, or if it is a bug with INI_SCANNER_RAW mode not properly ignoring them.
Regardless of the answer, at this point, fixing it will require me to write my own function to parse that ini file, so it could be some time before I'm able to address this further.
