### ISSUE TITLE
Script Runs Multiple Times

### ISSUE THREAD

**Issue by gitsnow** [JTok/unraid-vmbackup#7]
Hi,

I'm not sure if you're still maintaining this script, but I've tried setting the script to keep 2 backups, but instead of running once and keeping one existing backup, the backup script runs a second time and creates a second backup.  To clarify, every time the script runs, it creates two backups which defeats the purpose of setting the number of backups to keep if all the backups are from the same day.  I was wondering if you could shed some light if I have somehow configured the script wrong or if this is a bug?

**Comment by JTok** [comment]
I am having trouble replicating this issue. If you can send me the log file, I'll take a look and see what I can do.

**Comment by gitsnow** [comment]
Please disregard this issue.  I'm an idiot, it turns out it was a cron scheduling error that was making the script run multiple times.
